/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import java.awt.CardLayout;
import java.util.UUID;
import javax.swing.JPanel;
import model.Admin;
import model.MainSystem;

/**
 *
 * @author bharv
 */
public class adminScreen extends javax.swing.JPanel {

    /**
     * Creates new form doctorScreen
     */
    JPanel bottomPanel;
    MainSystem rootDataObj;

    public adminScreen(JPanel bottomPanel, MainSystem rootDataObj) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.rootDataObj = rootDataObj;
        loadAdminType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        subTitleLabel1 = new javax.swing.JLabel();
        adminType = new javax.swing.JLabel();
        adminTypeDrpdwn = new javax.swing.JComboBox<>();
        adminID = new javax.swing.JLabel();
        adminIDText = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("WELCOME ADMINS");

        subTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subTitleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitleLabel1.setText("Please Enter your Admin ID to login");

        adminType.setText("Admin Type:");

        adminTypeDrpdwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTypeDrpdwnActionPerformed(evt);
            }
        });

        adminID.setText("Admin ID:");

        adminIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminIDTextActionPerformed(evt);
            }
        });

        LoginBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subTitleLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminID)
                            .addComponent(adminType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminTypeDrpdwn, 0, 145, Short.MAX_VALUE)
                            .addComponent(adminIDText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminType)
                    .addComponent(adminTypeDrpdwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminID)
                    .addComponent(adminIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(LoginBtn)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminTypeDrpdwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTypeDrpdwnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTypeDrpdwnActionPerformed

    private void adminIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminIDTextActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        Admin selectedAdmin = null;
        for(Admin adminObj: this.rootDataObj.getRootAdminDirectory()) {
            if(adminObj.getType() == adminTypeDrpdwn.getSelectedItem()) {
                selectedAdmin = adminObj;
            }
        }
        
        if(selectedAdmin.getPersonId().toString() == null ? adminIDText.getText() == null : selectedAdmin.getPersonId().toString().equals(adminIDText.getText())) {
            selectoptionScreen patient = new selectoptionScreen(bottomPanel,selectedAdmin );
            bottomPanel.add("patientScreen", patient);
            CardLayout layout = (CardLayout) bottomPanel.getLayout();
            layout.next(bottomPanel);
        } else {
            System.out.println("error");
        }
        

//        Admin admin = new Admin();
//        admin.setType((String) adminTypeDrpdwn.getSelectedItem());
//        admin.setPersonId(UUID.fromString((adminIDText.getText())));

//        PatientRegisterScreen patientRegister = new PatientRegisterScreen(bottomPanel);
//        bottomPanel.add("selectoptionScreen", patientRegister);
//        CardLayout layout = (CardLayout) bottomPanel.getLayout();
//        layout.next(bottomPanel);
    }//GEN-LAST:event_LoginBtnActionPerformed
    private void loadAdminType() {
        for(Admin adminObj: this.rootDataObj.getRootAdminDirectory()) {
            adminTypeDrpdwn.addItem(adminObj.getType());
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel adminID;
    private javax.swing.JTextField adminIDText;
    private javax.swing.JLabel adminType;
    private javax.swing.JComboBox<String> adminTypeDrpdwn;
    private javax.swing.JLabel subTitleLabel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
