/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Admin;
import model.City;
import model.Community;
import model.Doctor;
import model.Encounter;
import model.EncounterDirectory;
import model.Hospital;
import model.House;
import model.MainSystem;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author bharv
 */
public class patientDetails extends javax.swing.JPanel {

    /**
     * Creates new form patientScreens
     */
    Admin admin;
    MainSystem rootDataObj;
     
    public patientDetails(Admin admin, MainSystem rootDataObj) {
        this.admin = admin;
        this.rootDataObj = rootDataObj;
        initComponents();
        populateCityValues();
        populateTable();
//        cityField.setSelectedIndex(-1);
//        communityField.setSelectedIndex(-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ViewBtn1 = new javax.swing.JButton();
        DeleteBtn1 = new javax.swing.JButton();
        search1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        emailLabel3 = new javax.swing.JLabel();
        phoneLabel3 = new javax.swing.JLabel();
        address3 = new javax.swing.JLabel();
        roadLabel3 = new javax.swing.JLabel();
        roadField = new javax.swing.JTextField();
        houseNumField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        cityLabel3 = new javax.swing.JLabel();
        UpdateBtn1 = new javax.swing.JButton();
        cityField = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cityLabel4 = new javax.swing.JLabel();
        communityField = new javax.swing.JComboBox<>();

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email ID", "Phone Number", "Area Name", "CIty", "PIN Code"
            }
        ));
        jScrollPane2.setViewportView(patientTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Patient Details Here");

        ViewBtn1.setText("VIEW");
        ViewBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtn1ActionPerformed(evt);
            }
        });

        DeleteBtn1.setText("DELETE");
        DeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn1ActionPerformed(evt);
            }
        });

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        nameLabel3.setText("Name:");

        emailLabel3.setText("Emaill ID:");

        phoneLabel3.setText("Phone Number:");

        address3.setText("House Number:");

        roadLabel3.setText("Road Name:");

        houseNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseNumFieldActionPerformed(evt);
            }
        });

        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneFieldKeyTyped(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        cityLabel3.setText("City:");

        UpdateBtn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UpdateBtn1.setText("Update Patient Information");
        UpdateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtn1ActionPerformed(evt);
            }
        });

        cityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cityLabel4.setText("Community:");

        communityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(ViewBtn1)
                            .addGap(18, 18, 18)
                            .addComponent(DeleteBtn1))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(search1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(address3)
                                .addGap(27, 27, 27)
                                .addComponent(houseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phoneLabel3)
                                    .addComponent(emailLabel3)
                                    .addComponent(nameLabel3))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(phoneField)
                                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roadLabel3)
                            .addComponent(cityLabel4)
                            .addComponent(cityLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roadField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cityField, 0, 200, Short.MAX_VALUE)
                            .addComponent(communityField, 0, 200, Short.MAX_VALUE)
                            .addComponent(UpdateBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBtn1)
                    .addComponent(DeleteBtn1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel3)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roadLabel3)
                            .addComponent(roadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel3)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cityLabel3)
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel3)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel4)
                    .addComponent(communityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address3)
                            .addComponent(houseNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(UpdateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean isValid(String val) {
        return val.equals("");
    }
    
    private void UpdateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = patientTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            Patient selectedPatient = (Patient) model.getValueAt(selectedIndex, 0);
            
            
            for (Hospital hospObj: this.rootDataObj.getRootHospitalDirectory()) {
                for (Encounter enc : hospObj.getEncounters().getEncounter()) {
                    System.out.println(enc.getPatient().getPersonId());
                    System.out.println(selectedPatient.getPersonId());
                    if(enc.getPatient().getPersonId() == selectedPatient.getPersonId()) {
                        if(isValid(nameField.getText()) || isValid(emailField.getText()) || isValid(phoneField.getText()) || 
                                isValid(houseNumField.getText()) || isValid(roadField.getText()) || cityField.getSelectedItem() == null || 
                            communityField.getSelectedItem() == null ) {
                            JOptionPane.showMessageDialog(this, "Fill all the fields");
                        } else {
                            Patient updatePat = enc.getPatient();
                            updatePat.setName(nameField.getText());
                            updatePat.setEmailId(emailField.getText());
                            updatePat.setPhoneNumber(Long.parseLong(phoneField.getText()));

                             House newHouse = new House();
                             newHouse.setHouseNumber(Integer.parseInt(houseNumField.getText()));
                             newHouse.setRoadName(roadField.getText());
                             updatePat.setHouse(newHouse);
                             City selectedCity = rootDataObj.getRootCityDirectory().get(cityField.getSelectedIndex());
                             updatePat.setCity(selectedCity);
                             updatePat.setCommunity(selectedCity.getCommunityDirectory().get(communityField.getSelectedIndex()));
                             JOptionPane.showMessageDialog(this, "Doctor updated successfully!");
                            populateTable();
                            nameField.setText("");
                            emailField.setText("");
                            phoneField.setText("");
                            houseNumField.setText("");
                            roadField.setText("");
                            communityField.setSelectedIndex(-1);
                            cityField.setSelectedIndex(-1);
                        }
                    }
                }
            }
           
        }
    }//GEN-LAST:event_UpdateBtn1ActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void houseNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseNumFieldActionPerformed

    private void DeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = patientTable.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted", "Error - No selection", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            Patient selectedPatient = (Patient) model.getValueAt(selectedIndex, 0);
            
            Hospital removeHosp = null;
            Encounter removeEnc = null;
            for (Hospital hospObj: this.rootDataObj.getRootHospitalDirectory()) {
                for (Encounter enc : hospObj.getEncounters().getEncounter()) {
                    System.out.println(enc.getPatient().getPersonId());
                    System.out.println(selectedPatient.getPersonId());
                    if(enc.getPatient().getPersonId() == selectedPatient.getPersonId()) {
                        removeHosp = hospObj;
                        removeEnc = enc;
                    }
                }
            }
            removeHosp.getEncounters().deleteEncounter(removeEnc);
            JOptionPane.showMessageDialog(this, "Patient is deleted successfully.");
            populateTable();
        }
    }//GEN-LAST:event_DeleteBtn1ActionPerformed

    private void ViewBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtn1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = patientTable.getSelectedRow();
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        Patient selectedPat = (Patient) model.getValueAt(selectedRowIndex, 0);
        nameField.setText(String.valueOf(selectedPat.getName()));
        emailField.setText(String.valueOf(selectedPat.getEmailId()));
        phoneField.setText(String.valueOf(selectedPat.getPhoneNumber()));
        houseNumField.setText(String.valueOf(selectedPat.getHouse().getHouseNumber()));
        roadField.setText(String.valueOf(selectedPat.getHouse().getRoadName()));
        cityField.setSelectedItem(String.valueOf(selectedPat.getCity().getCityName()));
        communityField.setSelectedItem(String.valueOf(selectedPat.getCommunity().getDistrict()));
        
    }//GEN-LAST:event_ViewBtn1ActionPerformed

    private void cityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityFieldActionPerformed
        // TODO add your handling code here:
        City selectedCity = this.rootDataObj.getRootCityDirectory().get(cityField.getSelectedIndex());
        communityField.removeAllItems();
         for (Community comm : selectedCity.getCommunityDirectory()) {
            communityField.addItem(comm.toString());
        }
    }//GEN-LAST:event_cityFieldActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        patientTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchField.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldKeyPressed

    private void communityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityFieldActionPerformed

    private void phoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyTyped
        // TODO add your handling code here:
         if (phoneField.getText().length() != 10) {
            phoneField.setForeground(Color.RED);
            phoneField.setForeground(Color.RED);
        } else {
            phoneField.setForeground(Color.BLACK);
            phoneField.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_phoneFieldKeyTyped

    private void populateCityValues() {
        for(City cityObj: this.rootDataObj.getRootCityDirectory()){
            cityField.addItem(cityObj.getCityName());
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        model.setRowCount(0);
        PatientDirectory tempPatientDirectory = new PatientDirectory();
        for (Hospital hospObj: this.rootDataObj.getRootHospitalDirectory()) {
            for (Encounter enc : hospObj.getEncounters().getEncounter()) {
                if (!tempPatientDirectory.getPatients().contains(enc.getPatient())) {
                    tempPatientDirectory.getPatients().add(enc.getPatient());
                }
            }
        }
        

        for (Patient pat : tempPatientDirectory.getPatients()) {
            Object[] row = new Object[6];
            row[0] = pat;
            row[1] = pat.getEmailId();
            row[2] = Long.toString(pat.getPhoneNumber());
            row[3] = pat.getCommunity().getAreaName();
            row[4] = pat.getCity().getCityName();
            row[5] = pat.getCity().getPinCode();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn1;
    private javax.swing.JButton UpdateBtn1;
    private javax.swing.JButton ViewBtn1;
    private javax.swing.JLabel address3;
    private javax.swing.JComboBox<String> cityField;
    private javax.swing.JLabel cityLabel3;
    private javax.swing.JLabel cityLabel4;
    private javax.swing.JComboBox<String> communityField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JTextField houseNumField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel3;
    private javax.swing.JTextField roadField;
    private javax.swing.JLabel roadLabel3;
    private javax.swing.JLabel search1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
