/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.doctor;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Doctor;
import model.Encounter;
import model.Hospital;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author bharv
 */
public class NewVitalSigns extends javax.swing.JPanel {

    /**
     * Creates new form NewVitalSigns
     */
    JPanel bottomPanel;
    Hospital selectedHospital;
    Doctor doctorLogin;
    Patient newPatient;

    public NewVitalSigns(JPanel bottomPanel, Doctor doctorLogin, Hospital selectedHospital, Patient newPatient) {
        this.bottomPanel = bottomPanel;
        this.selectedHospital = selectedHospital;
        this.doctorLogin = doctorLogin;
        this.newPatient = newPatient;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPText = new javax.swing.JTextField();
        PulseText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        personID = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        TempText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        PulseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulseTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter New Vital Signs");

        name.setText("Temperature:");

        emailID.setText("Blood Pressure:");

        phoneNumber.setText("Pulse:");

        personID.setText("Date:");

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaveBtn.setText("Save Vital Signs");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        TempText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneNumber)
                    .addComponent(emailID)
                    .addComponent(name)
                    .addComponent(personID))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SaveBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TempText)
                            .addComponent(BPText)
                            .addComponent(PulseText)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(TempText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumber)
                    .addComponent(PulseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personID)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(SaveBtn)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        try {
            VitalSigns userVitals = new VitalSigns();
            userVitals.setTemperature(Integer.parseInt(TempText.getText()));
            userVitals.setBloodPressure(Integer.parseInt(BPText.getText()));
            userVitals.setPulse(Integer.parseInt(PulseText.getText()));
            userVitals.setDateOfVitalEntry(jDateChooser1.getDate());

            // new encounter
            Encounter newEncounter = new Encounter();
            newEncounter.setDoctor(doctorLogin);
            newEncounter.setPatient(newPatient);
            newEncounter.setVitals(userVitals);

            //add encounter into encDir or current hospital
            selectedHospital.getEncounters().addEncounter(newEncounter);
            JOptionPane.showMessageDialog(this, "New Vital Signs Saved as new Encounter!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please enter correct details!");

        }
        //create encounter, add this into encounters of the hospital of the perticular community

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void TempTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempTextActionPerformed

    private void PulseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PulseTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPText;
    private javax.swing.JTextField PulseText;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TempText;
    private javax.swing.JLabel emailID;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel personID;
    private javax.swing.JLabel phoneNumber;
    // End of variables declaration//GEN-END:variables

    private NewVitalSigns() {
    }
}
